In [1]:
import pandas as pd
import datetime as dt

In [55]:
df = pd.read_csv('nba_games.csv', index_col=0)
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,36.0,88.0,0.409,8.0,32.0,0.250,19.0,25.0,...,31.6,27.3,138.0,107.0,CLE,102,1,2018,2017-10-17,True
1,240.0,240.0,38.0,83.0,0.458,5.0,22.0,0.227,21.0,25.0,...,34.7,29.9,129.0,112.0,BOS,99,0,2018,2017-10-17,False
2,240.0,240.0,47.0,97.0,0.485,15.0,41.0,0.366,13.0,19.0,...,31.7,32.6,250.0,127.0,GSW,121,1,2018,2017-10-17,True
3,240.0,240.0,43.0,80.0,0.538,16.0,30.0,0.533,19.0,21.0,...,18.2,31.2,152.0,126.0,HOU,122,0,2018,2017-10-17,False
4,240.0,240.0,29.0,73.0,0.397,9.0,30.0,0.300,23.0,29.0,...,25.0,28.3,138.0,100.0,DET,102,1,2018,2017-10-18,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7683,240.0,240.0,38.0,77.0,0.494,15.0,38.0,0.395,19.0,26.0,...,25.8,26.9,143.0,124.0,CHO,118,0,2021,2021-01-08,False
7684,240.0,240.0,38.0,87.0,0.437,11.0,34.0,0.324,14.0,21.0,...,17.0,29.6,113.0,112.0,NYK,89,1,2021,2021-01-08,False
7685,240.0,240.0,34.0,96.0,0.354,9.0,27.0,0.333,12.0,20.0,...,18.2,27.6,227.0,103.0,OKC,101,0,2021,2021-01-08,True
7686,240.0,240.0,34.0,89.0,0.382,8.0,29.0,0.276,14.0,16.0,...,25.0,37.4,233.0,104.0,HOU,132,1,2021,2021-01-08,True
7687,240.0,240.0,51.0,91.0,0.560,22.0,47.0,0.468,8.0,11.0,...,40.0,31.2,152.0,142.0,ORL,90,0,2021,2021-01-08,False

In [56]:
df.season.unique()

array([2018, 2019, 2020, 2021], dtype=int64)

In [4]:
df = df.sort_values("date")

In [5]:
df = df.reset_index(drop=True)

In [6]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,36.0,88.0,0.409,8.0,32.0,0.250,19.0,25.0,...,31.6,27.3,138.0,107.0,CLE,102,1,2018,2017-10-17,True
1,240.0,240.0,38.0,83.0,0.458,5.0,22.0,0.227,21.0,25.0,...,34.7,29.9,129.0,112.0,BOS,99,0,2018,2017-10-17,False
2,240.0,240.0,47.0,97.0,0.485,15.0,41.0,0.366,13.0,19.0,...,31.7,32.6,250.0,127.0,GSW,121,1,2018,2017-10-17,True
3,240.0,240.0,43.0,80.0,0.538,16.0,30.0,0.533,19.0,21.0,...,18.2,31.2,152.0,126.0,HOU,122,0,2018,2017-10-17,False
4,240.0,240.0,42.0,88.0,0.477,8.0,23.0,0.348,8.0,10.0,...,50.0,37.1,151.0,110.0,HOU,105,0,2018,2017-10-18,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3931,265.0,265.0,47.0,94.0,0.500,14.0,39.0,0.359,7.0,13.0,...,20.5,28.4,200.0,123.0,DET,11,1,2019,2019-01-16,True
3932,265.0,265.0,44.0,92.0,0.478,12.0,30.0,0.400,20.0,25.0,...,22.2,30.9,138.0,129.0,ORL,6,0,2019,2019-01-16,False
3933,240.0,240.0,41.0,92.0,0.446,7.0,29.0,0.241,19.0,21.0,...,26.0,30.4,162.0,121.0,BOS,117,1,2019,2019-01-16,False
3934,240.0,240.0,46.0,92.0,0.500,14.0,30.0,0.467,11.0,13.0,...,33.3,29.9,144.0,133.0,TOR,108,0,2019,2019-01-16,True
3935,265.0,265.0,45.0,105.0,0.429,23.0,70.0,0.329,29.0,34.0,...,50.0,34.8,156.0,131.0,BRK,14,0,2019,2019-01-16,False

In [7]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [8]:
# target indicates if the team lost their next game

def add_target(team):
    team ["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

In [9]:
df["target"][pd.isnull(df["target"])]

3893    NaN
3898    NaN
3901    NaN
3903    NaN
3906    NaN
3907    NaN
3908    NaN
3909    NaN
3911    NaN
3912    NaN
3914    NaN
3917    NaN
3918    NaN
3919    NaN
3920    NaN
3921    NaN
3922    NaN
3923    NaN
3924    NaN
3925    NaN
3926    NaN
3927    NaN
3928    NaN
3929    NaN
3930    NaN
3931    NaN
3932    NaN
3933    NaN
3934    NaN
3935    NaN
Name: target, dtype: object

In [10]:
def true_false_conversion(x):
    if x == True:
        return 1
    elif x == False:
        return 0
    else:
        return 2
df["target"] = df["target"].apply(true_false_conversion)

In [11]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,36.0,88.0,0.409,8.0,32.0,0.250,19.0,25.0,0.760,...,27.3,138.0,107.0,CLE,102,1,2018,2017-10-17,True,0
1,240.0,38.0,83.0,0.458,5.0,22.0,0.227,21.0,25.0,0.840,...,29.9,129.0,112.0,BOS,99,0,2018,2017-10-17,False,0
2,240.0,47.0,97.0,0.485,15.0,41.0,0.366,13.0,19.0,0.684,...,32.6,250.0,127.0,GSW,121,1,2018,2017-10-17,True,1
3,240.0,43.0,80.0,0.538,16.0,30.0,0.533,19.0,21.0,0.905,...,31.2,152.0,126.0,HOU,122,0,2018,2017-10-17,False,1
4,240.0,42.0,88.0,0.477,8.0,23.0,0.348,8.0,10.0,0.800,...,37.1,151.0,110.0,HOU,105,0,2018,2017-10-18,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3931,265.0,47.0,94.0,0.500,14.0,39.0,0.359,7.0,13.0,0.538,...,28.4,200.0,123.0,DET,11,1,2019,2019-01-16,True,2
3932,265.0,44.0,92.0,0.478,12.0,30.0,0.400,20.0,25.0,0.800,...,30.9,138.0,129.0,ORL,6,0,2019,2019-01-16,False,2
3933,240.0,41.0,92.0,0.446,7.0,29.0,0.241,19.0,21.0,0.905,...,30.4,162.0,121.0,BOS,117,1,2019,2019-01-16,False,2
3934,240.0,46.0,92.0,0.500,14.0,30.0,0.467,11.0,13.0,0.846,...,29.9,144.0,133.0,TOR,108,0,2019,2019-01-16,True,2
3935,265.0,45.0,105.0,0.429,23.0,70.0,0.329,29.0,34.0,0.853,...,34.8,156.0,131.0,BRK,14,0,2019,2019-01-16,False,2

In [12]:
df["won"].value_counts()

False    1981
True     1955
Name: won, dtype: int64

In [13]:
df["target"].value_counts()

0    1966
1    1940
2      30
Name: target, dtype: int64

In [14]:
# Check how many columns have null values
nulls = pd.isnull(df)

In [15]:
nulls = nulls.sum()

In [16]:
nulls = nulls[nulls > 0]

In [17]:
# Delete previous cell columns
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [18]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [19]:
df = df[valid_columns].copy()

In [20]:
# Feature Selection
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [21]:
removed_columns= ["season", "date", "won", "target", "team", "team_opp"]

In [22]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [23]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns] )

In [24]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [25]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.000000,0.378378,0.444444,0.329870,0.28,0.355932,0.246819,0.418605,0.380952,0.719953,...,0.064350,0.194030,0.394737,CLE,0.680272,1.0,2018,2017-10-17,True,0
1,0.000000,0.432432,0.351852,0.457143,0.16,0.186441,0.217557,0.465116,0.380952,0.813302,...,0.097812,0.149254,0.460526,BOS,0.659864,0.0,2018,2017-10-17,False,0
2,0.000000,0.675676,0.611111,0.527273,0.56,0.508475,0.394402,0.279070,0.285714,0.631272,...,0.132561,0.751244,0.657895,GSW,0.809524,1.0,2018,2017-10-17,True,1
3,0.000000,0.567568,0.296296,0.664935,0.60,0.322034,0.606870,0.418605,0.317460,0.889148,...,0.114543,0.263682,0.644737,HOU,0.816327,0.0,2018,2017-10-17,False,1
4,0.000000,0.540541,0.444444,0.506494,0.28,0.203390,0.371501,0.162791,0.142857,0.766628,...,0.190476,0.258706,0.434211,HOU,0.700680,0.0,2018,2017-10-18,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3931,0.333333,0.675676,0.555556,0.566234,0.52,0.474576,0.385496,0.139535,0.190476,0.460910,...,0.078507,0.502488,0.605263,DET,0.061224,1.0,2019,2019-01-16,True,2
3932,0.333333,0.594595,0.518519,0.509091,0.44,0.322034,0.437659,0.441860,0.380952,0.766628,...,0.110682,0.194030,0.684211,ORL,0.027211,0.0,2019,2019-01-16,False,2
3933,0.000000,0.513514,0.518519,0.425974,0.24,0.305085,0.235369,0.418605,0.317460,0.889148,...,0.104247,0.313433,0.578947,BOS,0.782313,1.0,2019,2019-01-16,False,2
3934,0.000000,0.648649,0.518519,0.566234,0.52,0.322034,0.522901,0.232558,0.190476,0.820303,...,0.097812,0.223881,0.736842,TOR,0.721088,0.0,2019,2019-01-16,True,2
3935,0.333333,0.621622,0.759259,0.381818,0.88,1.000000,0.347328,0.651163,0.523810,0.828471,...,0.160875,0.283582,0.710526,BRK,0.081633,0.0,2019,2019-01-16,False,2

In [26]:
predictors = list(selected_columns[sfs.get_support()])

In [27]:
predictors

['mp',
 'orb',
 'ast',
 'tov',
 'tov%',
 'usg%',
 'drtg',
 'ft%_max',
 'blk_max',
 'pf_max',
 'ts%_max',
 '3par_max',
 'orb%_max',
 'ortg_max',
 'mp_opp',
 '3p%_opp',
 'ast_opp',
 'efg%_opp',
 'usg%_opp',
 'ortg_opp',
 'ft%_max_opp',
 'orb_max_opp',
 'stl_max_opp',
 '+/-_max_opp',
 'ts%_max_opp',
 'efg%_max_opp',
 '3par_max_opp',
 'orb%_max_opp',
 'blk%_max_opp',
 'total_opp']

In [28]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    
    seasons = sorted(data["season"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        
        train = data[data["season"] < season]
        test = data[data["season"] == season]
        
        model.fit(train[predictors], train["target"])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [29]:
predictions = backtest(df, rr, predictors)

In [30]:
predictions

      actual  prediction
2618       1           1
2619       0           0
2620       1           0
2621       1           1
2622       0           0
...      ...         ...
3931       2           0
3932       2           1
3933       2           0
3934       2           0
3935       2           0

[1318 rows x 2 columns]

In [31]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["prediction"])

0.5372670807453416

In [32]:
df.groupby(["home"]).apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.469512
1.0    0.523882
dtype: float64

In [33]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [34]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.000000,0.378378,0.444444,0.329870,0.28,0.355932,0.246819,0.418605,0.380952,0.719953,...,0.060,0.245865,0.064350,0.194030,0.394737,0.680272,1.0,True,BOS,2018
1,0.000000,0.432432,0.351852,0.457143,0.16,0.186441,0.217557,0.465116,0.380952,0.813302,...,0.045,0.280044,0.097812,0.149254,0.460526,0.659864,0.0,False,CLE,2018
2,0.000000,0.675676,0.611111,0.527273,0.56,0.508475,0.394402,0.279070,0.285714,0.631272,...,0.091,0.246968,0.132561,0.751244,0.657895,0.809524,1.0,True,HOU,2018
3,0.000000,0.567568,0.296296,0.664935,0.60,0.322034,0.606870,0.418605,0.317460,0.889148,...,0.065,0.098126,0.114543,0.263682,0.644737,0.816327,0.0,False,GSW,2018
4,0.000000,0.540541,0.444444,0.506494,0.28,0.203390,0.371501,0.162791,0.142857,0.766628,...,0.072,0.448732,0.190476,0.258706,0.434211,0.700680,0.0,False,SAC,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3931,0.333333,0.675676,0.555556,0.566234,0.52,0.474576,0.385496,0.139535,0.190476,0.460910,...,0.048,0.123484,0.078507,0.502488,0.605263,0.061224,1.0,True,ORL,2019
3932,0.333333,0.594595,0.518519,0.509091,0.44,0.322034,0.437659,0.441860,0.380952,0.766628,...,0.057,0.142227,0.110682,0.194030,0.684211,0.027211,0.0,False,DET,2019
3933,0.000000,0.513514,0.518519,0.425974,0.24,0.305085,0.235369,0.418605,0.317460,0.889148,...,0.045,0.184123,0.104247,0.313433,0.578947,0.782313,1.0,False,TOR,2019
3934,0.000000,0.648649,0.518519,0.566234,0.52,0.322034,0.522901,0.232558,0.190476,0.820303,...,0.025,0.264609,0.097812,0.223881,0.736842,0.721088,0.0,True,BOS,2019
3935,0.333333,0.621622,0.759259,0.381818,0.88,1.000000,0.347328,0.651163,0.523810,0.828471,...,0.106,0.448732,0.160875,0.283582,0.710526,0.081633,0.0,False,HOU,2019

In [35]:
def find_team_averages(team):
    rolling = team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

C:\Users\User\AppData\Local\Temp\ipykernel_1012\4262171003.py:2: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['team'], dtype='object')
  rolling = team.rolling(10).mean()

In [36]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,season
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3931,0.033333,0.448649,0.412963,0.433247,0.384,0.345763,0.360305,0.362791,0.330159,0.699417,...,0.075401,0.0493,0.232745,0.142214,0.444279,0.485526,0.654422,0.7,0.7,2019.0
3932,0.033333,0.435135,0.424074,0.407792,0.440,0.400000,0.372519,0.351163,0.307937,0.744807,...,0.089840,0.1212,0.362183,0.154054,0.339303,0.523684,0.658503,0.7,0.3,2019.0
3933,0.066667,0.505405,0.488889,0.443896,0.384,0.344068,0.357761,0.462791,0.403175,0.769312,...,0.067246,0.0851,0.415766,0.138095,0.465672,0.540789,0.664626,0.5,0.7,2019.0
3934,0.000000,0.551351,0.450000,0.520779,0.484,0.391525,0.415267,0.313953,0.271429,0.781564,...,0.058690,0.0626,0.303197,0.166409,0.369154,0.594737,0.706122,0.5,0.5,2019.0
3935,0.066667,0.448649,0.405556,0.435844,0.676,0.637288,0.397964,0.544186,0.450794,0.809452,...,0.070722,0.0925,0.306615,0.129086,0.334826,0.661842,0.595918,0.4,0.5,2019.0

In [37]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df, df_rolling], axis=1)

In [38]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10
0,0.000000,0.378378,0.444444,0.329870,0.28,0.355932,0.246819,0.418605,0.380952,0.719953,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000000,0.432432,0.351852,0.457143,0.16,0.186441,0.217557,0.465116,0.380952,0.813302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.000000,0.675676,0.611111,0.527273,0.56,0.508475,0.394402,0.279070,0.285714,0.631272,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.000000,0.567568,0.296296,0.664935,0.60,0.322034,0.606870,0.418605,0.317460,0.889148,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.000000,0.540541,0.444444,0.506494,0.28,0.203390,0.371501,0.162791,0.142857,0.766628,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3931,0.333333,0.675676,0.555556,0.566234,0.52,0.474576,0.385496,0.139535,0.190476,0.460910,...,0.075401,0.0493,0.232745,0.142214,0.444279,0.485526,0.654422,0.7,0.7,2019.0
3932,0.333333,0.594595,0.518519,0.509091,0.44,0.322034,0.437659,0.441860,0.380952,0.766628,...,0.089840,0.1212,0.362183,0.154054,0.339303,0.523684,0.658503,0.7,0.3,2019.0
3933,0.000000,0.513514,0.518519,0.425974,0.24,0.305085,0.235369,0.418605,0.317460,0.889148,...,0.067246,0.0851,0.415766,0.138095,0.465672,0.540789,0.664626,0.5,0.7,2019.0
3934,0.000000,0.648649,0.518519,0.566234,0.52,0.322034,0.522901,0.232558,0.190476,0.820303,...,0.058690,0.0626,0.303197,0.166409,0.369154,0.594737,0.706122,0.5,0.5,2019.0
3935,0.333333,0.621622,0.759259,0.381818,0.88,1.000000,0.347328,0.651163,0.523810,0.828471,...,0.070722,0.0925,0.306615,0.129086,0.334826,0.661842,0.595918,0.4,0.5,2019.0

In [39]:
df = df.dropna()

In [40]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10
236,0.000000,0.324324,0.444444,0.270130,0.32,0.389831,0.265903,0.372093,0.333333,0.735123,...,0.079412,0.1126,0.357222,0.189318,0.381592,0.446053,0.717007,0.4,0.3,2018.0
251,0.000000,0.540541,0.462963,0.493506,0.60,0.610169,0.361323,0.418605,0.349206,0.796966,...,0.079278,0.1114,0.293054,0.128314,0.336816,0.536842,0.684354,0.7,0.5,2018.0
260,0.000000,0.486486,0.425926,0.462338,0.20,0.220339,0.246819,0.488372,0.412698,0.784131,...,0.068449,0.1056,0.316428,0.156242,0.437313,0.523684,0.709524,0.5,0.7,2018.0
261,0.000000,0.756757,0.500000,0.693506,0.68,0.491525,0.501272,0.186047,0.253968,0.450408,...,0.071390,0.0627,0.256560,0.124453,0.392040,0.677632,0.743537,0.6,0.6,2018.0
263,0.000000,0.486486,0.425926,0.462338,0.36,0.271186,0.399491,0.186047,0.174603,0.708285,...,0.078342,0.1045,0.356450,0.186358,0.343781,0.428947,0.713605,0.5,0.4,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3931,0.333333,0.675676,0.555556,0.566234,0.52,0.474576,0.385496,0.139535,0.190476,0.460910,...,0.075401,0.0493,0.232745,0.142214,0.444279,0.485526,0.654422,0.7,0.7,2019.0
3932,0.333333,0.594595,0.518519,0.509091,0.44,0.322034,0.437659,0.441860,0.380952,0.766628,...,0.089840,0.1212,0.362183,0.154054,0.339303,0.523684,0.658503,0.7,0.3,2019.0
3933,0.000000,0.513514,0.518519,0.425974,0.24,0.305085,0.235369,0.418605,0.317460,0.889148,...,0.067246,0.0851,0.415766,0.138095,0.465672,0.540789,0.664626,0.5,0.7,2019.0
3934,0.000000,0.648649,0.518519,0.566234,0.52,0.322034,0.522901,0.232558,0.190476,0.820303,...,0.058690,0.0626,0.303197,0.166409,0.369154,0.594737,0.706122,0.5,0.5,2019.0
3935,0.333333,0.621622,0.759259,0.381818,0.88,1.000000,0.347328,0.651163,0.523810,0.828471,...,0.070722,0.0925,0.306615,0.129086,0.334826,0.661842,0.595918,0.4,0.5,2019.0

In [41]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

C:\Users\User\AppData\Local\Temp\ipykernel_1012\1688004556.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df, "home")
C:\Users\User\AppData\Local\Temp\ipykernel_1012\1688004556.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["team_opp_next"] = add_col(df, "team_opp")
C:\Users\User\AppData\Local\Temp\ipykernel_1012\1688004556.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [42]:
df = df.copy()

In [43]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10,home_next,team_opp_next,date_next
236,0.000000,0.324324,0.444444,0.270130,0.32,0.389831,0.265903,0.372093,0.333333,0.735123,...,0.189318,0.381592,0.446053,0.717007,0.4,0.3,2018.0,0.0,MIN,2017-11-04
251,0.000000,0.540541,0.462963,0.493506,0.60,0.610169,0.361323,0.418605,0.349206,0.796966,...,0.128314,0.336816,0.536842,0.684354,0.7,0.5,2018.0,1.0,UTA,2017-11-05
260,0.000000,0.486486,0.425926,0.462338,0.20,0.220339,0.246819,0.488372,0.412698,0.784131,...,0.156242,0.437313,0.523684,0.709524,0.5,0.7,2018.0,1.0,BRK,2017-11-07
261,0.000000,0.756757,0.500000,0.693506,0.68,0.491525,0.501272,0.186047,0.253968,0.450408,...,0.124453,0.392040,0.677632,0.743537,0.6,0.6,2018.0,1.0,MIA,2017-11-06
263,0.000000,0.486486,0.425926,0.462338,0.36,0.271186,0.399491,0.186047,0.174603,0.708285,...,0.186358,0.343781,0.428947,0.713605,0.5,0.4,2018.0,0.0,WAS,2017-11-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3931,0.333333,0.675676,0.555556,0.566234,0.52,0.474576,0.385496,0.139535,0.190476,0.460910,...,0.142214,0.444279,0.485526,0.654422,0.7,0.7,2019.0,NaN,NaN,NaN
3932,0.333333,0.594595,0.518519,0.509091,0.44,0.322034,0.437659,0.441860,0.380952,0.766628,...,0.154054,0.339303,0.523684,0.658503,0.7,0.3,2019.0,NaN,NaN,NaN
3933,0.000000,0.513514,0.518519,0.425974,0.24,0.305085,0.235369,0.418605,0.317460,0.889148,...,0.138095,0.465672,0.540789,0.664626,0.5,0.7,2019.0,NaN,NaN,NaN
3934,0.000000,0.648649,0.518519,0.566234,0.52,0.322034,0.522901,0.232558,0.190476,0.820303,...,0.166409,0.369154,0.594737,0.706122,0.5,0.5,2019.0,NaN,NaN,NaN
3935,0.333333,0.621622,0.759259,0.381818,0.88,1.000000,0.347328,0.651163,0.523810,0.828471,...,0.129086,0.334826,0.661842,0.595918,0.4,0.5,2019.0,NaN,NaN,NaN

In [44]:
full = df.merge(
    df[rolling_cols + ["team_opp_next", "date_next", "team"]],
    left_on=["team", "date_next"],
    right_on=["team_opp_next", "date_next"]
)

In [45]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp_10_y,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,total_opp_10_y,home_opp_10_y,won_10_y,season_10_y,team_opp_next_y,team_y
0,0.000000,0.486486,0.425926,0.462338,0.20,0.220339,0.246819,0.488372,0.412698,0.784131,...,0.354024,0.134234,0.314925,0.498684,0.779592,0.5,0.5,2018.0,DEN,BRK
1,0.333333,0.351351,0.425926,0.311688,0.32,0.338983,0.297710,0.372093,0.333333,0.735123,...,0.254355,0.157272,0.415920,0.542105,0.728571,0.6,0.6,2018.0,NOP,IND
2,0.000000,0.486486,0.277778,0.581818,0.48,0.220339,0.618321,0.325581,0.333333,0.628938,...,0.249724,0.161647,0.421891,0.535526,0.719048,0.6,0.5,2018.0,DET,IND
3,0.000000,0.486486,0.388889,0.490909,0.32,0.271186,0.352417,0.395349,0.349206,0.746791,...,0.282690,0.130245,0.311443,0.544737,0.623810,0.6,0.3,2018.0,LAL,BOS
4,0.000000,0.486486,0.425926,0.462338,0.40,0.440678,0.306616,0.232558,0.206349,0.750292,...,0.287211,0.181596,0.303483,0.553947,0.608844,0.4,0.3,2018.0,MEM,POR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3341,0.000000,0.432432,0.407407,0.415584,0.36,0.525424,0.231552,0.511628,0.412698,0.827305,...,0.347078,0.137580,0.367164,0.452632,0.694558,0.5,0.5,2019.0,HOU,MEM
3342,0.000000,0.351351,0.481481,0.277922,0.40,0.423729,0.318066,0.279070,0.238095,0.781797,...,0.237707,0.145689,0.438806,0.485526,0.706122,0.6,0.6,2019.0,DET,ORL
3343,0.000000,0.405405,0.370370,0.410390,0.68,0.627119,0.405852,0.441860,0.333333,0.893816,...,0.264939,0.138095,0.360697,0.525000,0.664626,0.6,0.7,2019.0,HOU,BRK
3344,0.000000,0.405405,0.407407,0.384416,0.48,0.457627,0.363868,0.488372,0.380952,0.859977,...,0.273870,0.120463,0.406468,0.673684,0.663265,0.4,0.6,2019.0,BRK,HOU
3345,0.000000,0.405405,0.500000,0.324675,0.40,0.423729,0.318066,0.372093,0.349206,0.695449,...,0.447850,0.137709,0.451741,0.546053,0.655782,0.5,0.8,2019.0,BOS,TOR

In [46]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

     team_x team_opp_next_x team_y team_opp_next_y   date_next
0       DEN             BRK    BRK             DEN  2017-11-07
1       NOP             IND    IND             NOP  2017-11-07
2       DET             IND    IND             DET  2017-11-08
3       LAL             BOS    BOS             LAL  2017-11-08
4       MEM             POR    POR             MEM  2017-11-07
...     ...             ...    ...             ...         ...
3341    HOU             MEM    MEM             HOU  2019-01-14
3342    DET             ORL    ORL             DET  2019-01-16
3343    HOU             BRK    BRK             HOU  2019-01-16
3344    BRK             HOU    HOU             BRK  2019-01-16
3345    BOS             TOR    TOR             BOS  2019-01-16

[3346 rows x 5 columns]

In [47]:
removed_columns = list(full.columns[full.dtypes=="object"]) + removed_columns

In [48]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_opp_next_x',
 'date_next',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [49]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [50]:
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [51]:
predictors = list(selected_columns[sfs.get_support()])

In [52]:
predictors

['usg%',
 'orb%_max',
 'usg%_opp',
 'trb%_max_opp',
 'fg%_10_x',
 'efg%_10_x',
 'trb%_10_x',
 'usg%_10_x',
 'ast%_max_10_x',
 'stl%_max_10_x',
 'tov%_max_10_x',
 'stl_opp_10_x',
 'usg%_opp_10_x',
 '3p%_max_opp_10_x',
 'fta_max_opp_10_x',
 '+/-_max_opp_10_x',
 'stl%_max_opp_10_x',
 'total_opp_10_x',
 'season_10_x',
 'usg%_10_y',
 'stl%_max_10_y',
 'tov%_max_10_y',
 '3pa_opp_10_y',
 'ft_opp_10_y',
 'usg%_opp_10_y',
 'ft_max_opp_10_y',
 'fta_max_opp_10_y',
 'stl_max_opp_10_y',
 'total_opp_10_y',
 'season_10_y']

In [53]:
predictions = backtest(full, rr, predictors)

In [54]:
accuracy_score(predictions["actual"], predictions["prediction"])

0.49901574803149606