In [44]:
import pandas as pd
import datetime as dt

In [45]:
df = pd.read_csv('nba_games.csv', index_col=0)
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,265.0,265.0,43.0,102.0,0.422,19.0,45.0,0.422,17.0,20.0,...,22.2,35.7,158.0,114.0,TOR,13,1,2020,2019-10-22,True
1,265.0,265.0,42.0,103.0,0.408,14.0,40.0,0.350,32.0,38.0,...,25.0,37.7,146.0,124.0,NOP,5,0,2020,2019-10-22,False
2,240.0,240.0,37.0,85.0,0.435,13.0,33.0,0.394,15.0,21.0,...,22.2,42.4,203.0,116.0,LAC,112,1,2020,2019-10-22,False
3,240.0,240.0,42.0,81.0,0.519,11.0,31.0,0.355,17.0,24.0,...,25.0,35.8,300.0,125.0,LAL,102,0,2020,2019-10-22,True
4,240.0,240.0,49.0,105.0,0.467,9.0,30.0,0.300,18.0,22.0,...,100.0,32.6,208.0,128.0,CHO,126,1,2020,2019-10-23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,240.0,240.0,41.0,84.0,0.488,11.0,32.0,0.344,20.0,24.0,...,50.0,34.3,173.0,128.0,DEN,117,0,2021,2021-01-25,False
2762,240.0,240.0,44.0,87.0,0.506,15.0,29.0,0.517,16.0,20.0,...,33.3,32.9,148.0,124.0,CHI,103,1,2021,2021-01-25,True
2763,240.0,240.0,41.0,88.0,0.466,17.0,39.0,0.436,4.0,10.0,...,50.0,38.3,232.0,112.0,BOS,119,0,2021,2021-01-25,False
2764,240.0,240.0,39.0,94.0,0.415,8.0,24.0,0.333,22.0,25.0,...,100.0,32.6,208.0,114.0,GSW,130,1,2021,2021-01-25,False
2765,240.0,240.0,44.0,89.0,0.494,14.0,30.0,0.467,28.0,37.0,...,100.0,30.7,221.0,136.0,MIN,108,0,2021,2021-01-25,True

In [46]:
df.season.unique()

array([2020, 2021], dtype=int64)

In [47]:
df = df.sort_values("date")

In [48]:
df = df.reset_index(drop=True)

In [49]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,265.0,265.0,43.0,102.0,0.422,19.0,45.0,0.422,17.0,20.0,...,22.2,35.7,158.0,114.0,TOR,13,1,2020,2019-10-22,True
1,265.0,265.0,42.0,103.0,0.408,14.0,40.0,0.350,32.0,38.0,...,25.0,37.7,146.0,124.0,NOP,5,0,2020,2019-10-22,False
2,240.0,240.0,37.0,85.0,0.435,13.0,33.0,0.394,15.0,21.0,...,22.2,42.4,203.0,116.0,LAC,112,1,2020,2019-10-22,False
3,240.0,240.0,42.0,81.0,0.519,11.0,31.0,0.355,17.0,24.0,...,25.0,35.8,300.0,125.0,LAL,102,0,2020,2019-10-22,True
4,240.0,240.0,36.0,87.0,0.414,7.0,28.0,0.250,21.0,23.0,...,30.4,33.9,158.0,109.0,DEN,108,0,2020,2019-10-23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,240.0,240.0,35.0,70.0,0.500,17.0,38.0,0.447,32.0,38.0,...,16.2,35.6,223.0,139.0,PHI,104,0,2021,2021-01-25,True
2762,240.0,240.0,40.0,94.0,0.426,9.0,28.0,0.321,15.0,20.0,...,43.6,30.3,180.0,121.0,DET,119,1,2021,2021-01-25,False
2763,240.0,240.0,39.0,94.0,0.415,8.0,24.0,0.333,22.0,25.0,...,100.0,32.6,208.0,114.0,GSW,130,1,2021,2021-01-25,False
2764,240.0,240.0,31.0,84.0,0.369,11.0,43.0,0.256,12.0,17.0,...,19.7,30.8,153.0,99.0,BRK,98,1,2021,2021-01-25,False
2765,240.0,240.0,44.0,89.0,0.494,14.0,30.0,0.467,28.0,37.0,...,100.0,30.7,221.0,136.0,MIN,108,0,2021,2021-01-25,True

In [50]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [51]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,265.0,43.0,102.0,0.422,19.0,45.0,0.422,17.0,20.0,0.850,...,22.2,35.7,158.0,114.0,TOR,13,1,2020,2019-10-22,True
1,265.0,42.0,103.0,0.408,14.0,40.0,0.350,32.0,38.0,0.842,...,25.0,37.7,146.0,124.0,NOP,5,0,2020,2019-10-22,False
2,240.0,37.0,85.0,0.435,13.0,33.0,0.394,15.0,21.0,0.714,...,22.2,42.4,203.0,116.0,LAC,112,1,2020,2019-10-22,False
3,240.0,42.0,81.0,0.519,11.0,31.0,0.355,17.0,24.0,0.708,...,25.0,35.8,300.0,125.0,LAL,102,0,2020,2019-10-22,True
4,240.0,36.0,87.0,0.414,7.0,28.0,0.250,21.0,23.0,0.913,...,30.4,33.9,158.0,109.0,DEN,108,0,2020,2019-10-23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,240.0,35.0,70.0,0.500,17.0,38.0,0.447,32.0,38.0,0.842,...,16.2,35.6,223.0,139.0,PHI,104,0,2021,2021-01-25,True
2762,240.0,40.0,94.0,0.426,9.0,28.0,0.321,15.0,20.0,0.750,...,43.6,30.3,180.0,121.0,DET,119,1,2021,2021-01-25,False
2763,240.0,39.0,94.0,0.415,8.0,24.0,0.333,22.0,25.0,0.880,...,100.0,32.6,208.0,114.0,GSW,130,1,2021,2021-01-25,False
2764,240.0,31.0,84.0,0.369,11.0,43.0,0.256,12.0,17.0,0.706,...,19.7,30.8,153.0,99.0,BRK,98,1,2021,2021-01-25,False
2765,240.0,44.0,89.0,0.494,14.0,30.0,0.467,28.0,37.0,0.757,...,100.0,30.7,221.0,136.0,MIN,108,0,2021,2021-01-25,True

In [52]:
# target indicates if the team lost their next game

def add_target(team):
    team ["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

In [53]:
df["target"][pd.isnull(df["target"])]

2657    NaN
2701    NaN
2722    NaN
2724    NaN
2726    NaN
2731    NaN
2736    NaN
2737    NaN
2738    NaN
2739    NaN
2740    NaN
2742    NaN
2745    NaN
2746    NaN
2750    NaN
2751    NaN
2752    NaN
2753    NaN
2754    NaN
2755    NaN
2756    NaN
2757    NaN
2758    NaN
2759    NaN
2760    NaN
2761    NaN
2762    NaN
2763    NaN
2764    NaN
2765    NaN
Name: target, dtype: object

In [54]:
def true_false_conversion(x):
    if x == True:
        return 1
    elif x == False:
        return 0
    else:
        return 2
df["target"] = df["target"].apply(true_false_conversion)

In [55]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,265.0,43.0,102.0,0.422,19.0,45.0,0.422,17.0,20.0,0.850,...,35.7,158.0,114.0,TOR,13,1,2020,2019-10-22,True,0
1,265.0,42.0,103.0,0.408,14.0,40.0,0.350,32.0,38.0,0.842,...,37.7,146.0,124.0,NOP,5,0,2020,2019-10-22,False,0
2,240.0,37.0,85.0,0.435,13.0,33.0,0.394,15.0,21.0,0.714,...,42.4,203.0,116.0,LAC,112,1,2020,2019-10-22,False,1
3,240.0,42.0,81.0,0.519,11.0,31.0,0.355,17.0,24.0,0.708,...,35.8,300.0,125.0,LAL,102,0,2020,2019-10-22,True,1
4,240.0,36.0,87.0,0.414,7.0,28.0,0.250,21.0,23.0,0.913,...,33.9,158.0,109.0,DEN,108,0,2020,2019-10-23,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,240.0,35.0,70.0,0.500,17.0,38.0,0.447,32.0,38.0,0.842,...,35.6,223.0,139.0,PHI,104,0,2021,2021-01-25,True,2
2762,240.0,40.0,94.0,0.426,9.0,28.0,0.321,15.0,20.0,0.750,...,30.3,180.0,121.0,DET,119,1,2021,2021-01-25,False,2
2763,240.0,39.0,94.0,0.415,8.0,24.0,0.333,22.0,25.0,0.880,...,32.6,208.0,114.0,GSW,130,1,2021,2021-01-25,False,2
2764,240.0,31.0,84.0,0.369,11.0,43.0,0.256,12.0,17.0,0.706,...,30.8,153.0,99.0,BRK,98,1,2021,2021-01-25,False,2
2765,240.0,44.0,89.0,0.494,14.0,30.0,0.467,28.0,37.0,0.757,...,30.7,221.0,136.0,MIN,108,0,2021,2021-01-25,True,2

In [56]:
df["won"].value_counts()

False    1393
True     1373
Name: won, dtype: int64

In [57]:
df["target"].value_counts()

0    1378
1    1358
2      30
Name: target, dtype: int64

In [58]:
# Check how many columns have null values
nulls = pd.isnull(df)

In [59]:
nulls = nulls.sum()

In [60]:
nulls = nulls[nulls > 0]

In [61]:
# Delete previous cell columns
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [62]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [63]:
df = df[valid_columns].copy()

In [64]:
# Feature Selection
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [65]:
removed_columns= ["season", "date", "won", "target", "team", "team_opp"]

In [66]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [67]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns] )

In [68]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [69]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.5,0.564103,0.735849,0.377778,0.629630,0.659574,0.567839,0.350,0.319149,0.775112,...,0.159477,0.275510,0.4250,TOR,0.075949,1.0,2020,2019-10-22,True,0
1,0.5,0.538462,0.754717,0.343210,0.444444,0.553191,0.447236,0.725,0.702128,0.763118,...,0.185621,0.214286,0.5500,NOP,0.025316,0.0,2020,2019-10-22,False,0
2,0.0,0.410256,0.415094,0.409877,0.407407,0.404255,0.520938,0.300,0.340426,0.571214,...,0.247059,0.505102,0.4500,LAC,0.702532,1.0,2020,2019-10-22,False,1
3,0.0,0.538462,0.339623,0.617284,0.333333,0.361702,0.455611,0.350,0.404255,0.562219,...,0.160784,1.000000,0.5625,LAL,0.639241,0.0,2020,2019-10-22,True,1
4,0.0,0.384615,0.452830,0.358025,0.185185,0.297872,0.279732,0.450,0.382979,0.869565,...,0.135948,0.275510,0.3625,DEN,0.677215,0.0,2020,2019-10-23,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,0.0,0.358974,0.132075,0.570370,0.555556,0.510638,0.609715,0.725,0.702128,0.763118,...,0.158170,0.607143,0.7375,PHI,0.651899,0.0,2021,2021-01-25,True,2
2762,0.0,0.487179,0.584906,0.387654,0.259259,0.297872,0.398660,0.300,0.319149,0.625187,...,0.088889,0.387755,0.5125,DET,0.746835,1.0,2021,2021-01-25,False,2
2763,0.0,0.461538,0.584906,0.360494,0.222222,0.212766,0.418760,0.475,0.425532,0.820090,...,0.118954,0.530612,0.4250,GSW,0.816456,1.0,2021,2021-01-25,False,2
2764,0.0,0.256410,0.396226,0.246914,0.333333,0.617021,0.289782,0.225,0.255319,0.559220,...,0.095425,0.250000,0.2375,BRK,0.613924,1.0,2021,2021-01-25,False,2
2765,0.0,0.589744,0.490566,0.555556,0.444444,0.340426,0.643216,0.625,0.680851,0.635682,...,0.094118,0.596939,0.7000,MIN,0.677215,0.0,2021,2021-01-25,True,2

In [70]:
predictors = list(selected_columns[sfs.get_support()])

In [71]:
predictors

['mp',
 'fg%',
 'fta',
 'ast',
 'pts',
 'orb%',
 'usg%',
 'ortg',
 'fga_max',
 'fta_max',
 'ast_max',
 'blk_max',
 'tov_max',
 '+/-_max',
 'drb%_max',
 'tov%_max',
 'total',
 'mp_opp',
 'fta_opp',
 'pf_opp',
 'drb%_opp',
 'usg%_opp',
 'drtg_opp',
 'ft%_max_opp',
 'orb_max_opp',
 'tov_max_opp',
 '+/-_max_opp',
 'orb%_max_opp',
 'trb%_max_opp',
 'drtg_max_opp']

In [72]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    
    seasons = sorted(data["season"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        
        train = data[data["season"] < season]
        test = data[data["season"] == season]
        
        model.fit(train[predictors], train["target"])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [73]:
predictions = backtest(df, rr, predictors)

ValueError: No objects to concatenate