In [41]:
import pandas as pd
import datetime as dt

In [42]:
df = pd.read_csv('nba_games.csv', index_col=0)
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,True
1,240.0,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,False
2,240.0,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
3,240.0,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
4,240.0,240.0,45.0,90.0,0.500,16.0,44.0,0.364,8.0,15.0,...,33.3,100.0,150.0,122.0,CLE,121,1,2021,2020-12-23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2337,240.0,240.0,39.0,97.0,0.402,7.0,29.0,0.241,24.0,29.0,...,27.8,43.4,224.0,124.0,PHO,103,0,2021,2021-07-14,True
2338,240.0,240.0,50.0,87.0,0.575,14.0,28.0,0.500,9.0,17.0,...,25.0,43.1,161.0,141.0,PHO,119,1,2021,2021-07-17,True
2339,240.0,240.0,48.0,87.0,0.552,13.0,19.0,0.684,10.0,11.0,...,50.0,31.2,206.0,135.0,MIL,123,0,2021,2021-07-17,False
2340,240.0,240.0,38.0,86.0,0.442,6.0,25.0,0.240,16.0,19.0,...,50.0,39.5,149.0,107.0,MIL,105,1,2021,2021-07-20,True
2341,240.0,240.0,37.0,82.0,0.451,6.0,27.0,0.222,25.0,29.0,...,20.5,29.7,158.0,115.0,PHO,98,0,2021,2021-07-20,False

In [43]:
df.season.unique()

array([2021], dtype=int64)

In [44]:
df = df.sort_values("date")

In [45]:
df = df.reset_index(drop=True)

In [46]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,True
1,240.0,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,False
2,240.0,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
3,240.0,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
4,240.0,240.0,38.0,79.0,0.481,11.0,30.0,0.367,19.0,27.0,...,100.0,40.1,206.0,111.0,DAL,102,0,2021,2020-12-23,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2337,240.0,240.0,39.0,97.0,0.402,7.0,29.0,0.241,24.0,29.0,...,27.8,43.4,224.0,124.0,PHO,103,0,2021,2021-07-14,True
2338,240.0,240.0,50.0,87.0,0.575,14.0,28.0,0.500,9.0,17.0,...,25.0,43.1,161.0,141.0,PHO,119,1,2021,2021-07-17,True
2339,240.0,240.0,48.0,87.0,0.552,13.0,19.0,0.684,10.0,11.0,...,50.0,31.2,206.0,135.0,MIL,123,0,2021,2021-07-17,False
2340,240.0,240.0,38.0,86.0,0.442,6.0,25.0,0.240,16.0,19.0,...,50.0,39.5,149.0,107.0,MIL,105,1,2021,2021-07-20,True
2341,240.0,240.0,37.0,82.0,0.451,6.0,27.0,0.222,25.0,29.0,...,20.5,29.7,158.0,115.0,PHO,98,0,2021,2021-07-20,False

In [47]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [48]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,True
1,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,False
2,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
3,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
4,240.0,38.0,79.0,0.481,11.0,30.0,0.367,19.0,27.0,0.704,...,100.0,40.1,206.0,111.0,DAL,102,0,2021,2020-12-23,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2337,240.0,39.0,97.0,0.402,7.0,29.0,0.241,24.0,29.0,0.828,...,27.8,43.4,224.0,124.0,PHO,103,0,2021,2021-07-14,True
2338,240.0,50.0,87.0,0.575,14.0,28.0,0.500,9.0,17.0,0.529,...,25.0,43.1,161.0,141.0,PHO,119,1,2021,2021-07-17,True
2339,240.0,48.0,87.0,0.552,13.0,19.0,0.684,10.0,11.0,0.909,...,50.0,31.2,206.0,135.0,MIL,123,0,2021,2021-07-17,False
2340,240.0,38.0,86.0,0.442,6.0,25.0,0.240,16.0,19.0,0.842,...,50.0,39.5,149.0,107.0,MIL,105,1,2021,2021-07-20,True
2341,240.0,37.0,82.0,0.451,6.0,27.0,0.222,25.0,29.0,0.862,...,20.5,29.7,158.0,115.0,PHO,98,0,2021,2021-07-20,False

In [49]:
# target indicates if the team lost their next game

def add_target(team):
    team ["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

In [50]:
df["target"][pd.isnull(df["target"])]

2130    NaN
2132    NaN
2134    NaN
2138    NaN
2142    NaN
2144    NaN
2146    NaN
2149    NaN
2156    NaN
2158    NaN
2160    NaN
2165    NaN
2169    NaN
2171    NaN
2217    NaN
2236    NaN
2245    NaN
2248    NaN
2249    NaN
2250    NaN
2253    NaN
2260    NaN
2285    NaN
2300    NaN
2303    NaN
2304    NaN
2324    NaN
2329    NaN
2340    NaN
2341    NaN
Name: target, dtype: object

In [51]:
def true_false_conversion(x):
    if x == True:
        return 1
    elif x == False:
        return 0
    else:
        return 2
df["target"] = df["target"].apply(true_false_conversion)

In [52]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,True,1
1,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,False,0
2,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True,1
3,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False,1
4,240.0,38.0,79.0,0.481,11.0,30.0,0.367,19.0,27.0,0.704,...,40.1,206.0,111.0,DAL,102,0,2021,2020-12-23,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2337,240.0,39.0,97.0,0.402,7.0,29.0,0.241,24.0,29.0,0.828,...,43.4,224.0,124.0,PHO,103,0,2021,2021-07-14,True,1
2338,240.0,50.0,87.0,0.575,14.0,28.0,0.500,9.0,17.0,0.529,...,43.1,161.0,141.0,PHO,119,1,2021,2021-07-17,True,0
2339,240.0,48.0,87.0,0.552,13.0,19.0,0.684,10.0,11.0,0.909,...,31.2,206.0,135.0,MIL,123,0,2021,2021-07-17,False,1
2340,240.0,38.0,86.0,0.442,6.0,25.0,0.240,16.0,19.0,0.842,...,39.5,149.0,107.0,MIL,105,1,2021,2021-07-20,True,2
2341,240.0,37.0,82.0,0.451,6.0,27.0,0.222,25.0,29.0,0.862,...,29.7,158.0,115.0,PHO,98,0,2021,2021-07-20,False,2

In [53]:
df["won"].value_counts()

False    1178
True     1164
Name: won, dtype: int64

In [54]:
df["target"].value_counts()

0    1163
1    1149
2      30
Name: target, dtype: int64

In [55]:
# Check how many columns have null values
nulls = pd.isnull(df)

In [56]:
nulls = nulls.sum()

In [57]:
nulls = nulls[nulls > 0]

In [58]:
# Delete previous cell columns
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [59]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [60]:
df = df[valid_columns].copy()

In [61]:
# Feature Selection
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [62]:
removed_columns= ["season", "date", "won", "target", "team", "team_opp"]

In [63]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [64]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns] )

In [65]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [66]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.350,0.673469,0.256614,0.296296,0.433962,0.366057,0.342857,0.441860,0.491228,...,0.221932,1.000000,0.168831,BRK,0.809211,1.0,2021,2020-12-22,True,1
1,0.0,0.475,0.530612,0.476190,0.481481,0.471698,0.575707,0.657143,0.651163,0.726608,...,0.113577,0.829897,0.454545,GSW,0.638158,0.0,2021,2020-12-22,False,0
2,0.0,0.525,0.551020,0.518519,0.444444,0.566038,0.444260,0.314286,0.348837,0.615497,...,0.163185,0.309278,0.428571,LAL,0.703947,1.0,2021,2020-12-22,True,1
3,0.0,0.375,0.306122,0.507937,0.259259,0.358491,0.377704,0.600000,0.627907,0.669591,...,0.219321,0.247423,0.376623,LAC,0.750000,0.0,2021,2020-12-22,False,1
4,0.0,0.375,0.265306,0.539683,0.333333,0.377358,0.472546,0.457143,0.534884,0.567251,...,0.218016,0.515464,0.337662,DAL,0.657895,0.0,2021,2020-12-23,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2337,0.0,0.400,0.632653,0.330688,0.185185,0.358491,0.262895,0.600000,0.581395,0.748538,...,0.261097,0.608247,0.506494,PHO,0.664474,0.0,2021,2021-07-14,True,1
2338,0.0,0.675,0.428571,0.788360,0.444444,0.339623,0.693844,0.171429,0.302326,0.311404,...,0.257180,0.283505,0.727273,PHO,0.769737,1.0,2021,2021-07-17,True,0
2339,0.0,0.625,0.428571,0.727513,0.407407,0.169811,1.000000,0.200000,0.162791,0.866959,...,0.101828,0.515464,0.649351,MIL,0.796053,0.0,2021,2021-07-17,False,1
2340,0.0,0.375,0.408163,0.436508,0.148148,0.283019,0.261231,0.371429,0.348837,0.769006,...,0.210183,0.221649,0.285714,MIL,0.677632,1.0,2021,2021-07-20,True,2
2341,0.0,0.350,0.326531,0.460317,0.148148,0.320755,0.231281,0.628571,0.581395,0.798246,...,0.082245,0.268041,0.389610,PHO,0.631579,0.0,2021,2021-07-20,False,2

In [67]:
predictors = list(selected_columns[sfs.get_support()])

In [68]:
predictors

['mp',
 '3p',
 'pf',
 'usg%',
 'ortg',
 'fg%_max',
 'drb_max',
 'blk_max',
 '+/-_max',
 'trb%_max',
 'total',
 'mp_opp',
 'fg_opp',
 'fg%_opp',
 '3p_opp',
 'ft%_opp',
 'ast_opp',
 'stl_opp',
 'tov_opp',
 'pf_opp',
 'efg%_opp',
 'ast%_opp',
 'stl%_opp',
 'tov%_opp',
 'usg%_opp',
 'drtg_opp',
 '3p_max_opp',
 'ast%_max_opp',
 'stl%_max_opp',
 'total_opp']

In [69]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    
    seasons = sorted(data["season"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        
        train = data[data["season"] < season]
        test = data[data["season"] == season]
        
        model.fit(train[predictors], train["target"])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [70]:
predictions = backtest(df, rr, predictors)

ValueError: No objects to concatenate

In [ ]:
predictions

In [ ]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["predictions"])

In [ ]:
df.groupby(["home"]).apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

In [ ]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [ ]:
df_rolling

In [ ]:
def find_team_averages(team):
    rolling = team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

In [ ]:
df_rolling

In [ ]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df, df_rolling], axis=1)

In [ ]:
df

In [ ]:
df = df.dropna()

In [ ]:
df

In [ ]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x: shift(x, col_name))

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

In [ ]:
df = df.copy()

In [ ]:
full = df.merge(
    df[rolling_cols + ["team_opp_next", "date_next", "team"]],
    left_on=["team", "date_next"],
    right_on=["team_opp_next", "date_next"]
)

In [ ]:
full

In [ ]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

In [ ]:
removed_columns = list(full.columns[full.dtypes=="object"]) + removed_columns

In [ ]:
removed_columns

In [ ]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [ ]:
sfs.fit(full[selected_columns], full["target"])

In [ ]:
predictors = list(selected_columns[sfs.get_support()])

In [ ]:
predictors

In [ ]:
predictions = backtest(full, rr, predictors)

In [ ]:
accuracy_score(predictions["acutal"], predictions["predictions"])