In [140]:
import pandas as pd

In [141]:
df = pd.read_csv('nba_games.csv', index_col=0)
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,True
1,240.0,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,False
2,240.0,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
3,240.0,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
4,240.0,240.0,45.0,90.0,0.500,16.0,44.0,0.364,8.0,15.0,...,33.3,100.0,150.0,122.0,CLE,121,1,2021,2020-12-23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,240.0,240.0,34.0,83.0,0.410,17.0,52.0,0.327,15.0,21.0,...,69.4,36.4,111.0,110.0,NYK,83,0,2021,2020-12-31,False
130,240.0,240.0,44.0,91.0,0.484,13.0,36.0,0.361,12.0,19.0,...,60.0,27.3,178.0,125.0,OKC,80,1,2021,2020-12-31,False
131,240.0,240.0,30.0,80.0,0.375,15.0,48.0,0.313,5.0,15.0,...,41.0,35.8,154.0,94.0,NOP,113,0,2021,2020-12-31,True
132,240.0,240.0,41.0,84.0,0.488,17.0,33.0,0.515,7.0,10.0,...,30.7,33.8,135.0,118.0,UTA,95,1,2021,2020-12-31,False
133,240.0,240.0,35.0,84.0,0.417,12.0,34.0,0.353,13.0,19.0,...,23.0,34.3,182.0,110.0,PHO,106,0,2021,2020-12-31,True

In [142]:
df = df.sort_values("date")

In [143]:
df = df.reset_index(drop=True)

In [144]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,True
1,240.0,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,False
2,240.0,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
3,240.0,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
4,240.0,240.0,38.0,79.0,0.481,11.0,30.0,0.367,19.0,27.0,...,100.0,40.1,206.0,111.0,DAL,102,0,2021,2020-12-23,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,240.0,240.0,50.0,92.0,0.543,14.0,36.0,0.389,19.0,25.0,...,100.0,32.9,185.0,133.0,WAS,130,1,2021,2020-12-31,True
130,240.0,240.0,42.0,87.0,0.483,16.0,35.0,0.457,19.0,24.0,...,50.0,46.6,187.0,128.0,CLE,99,0,2021,2020-12-31,False
131,240.0,240.0,37.0,82.0,0.451,12.0,23.0,0.522,13.0,24.0,...,40.0,38.7,300.0,111.0,IND,119,1,2021,2020-12-31,True
132,240.0,240.0,33.0,95.0,0.347,7.0,28.0,0.250,19.0,21.0,...,50.0,28.8,150.0,98.0,PHI,116,0,2021,2020-12-31,True
133,240.0,240.0,35.0,84.0,0.417,12.0,34.0,0.353,13.0,19.0,...,23.0,34.3,182.0,110.0,PHO,106,0,2021,2020-12-31,True

In [145]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [146]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,True
1,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,False
2,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
3,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
4,240.0,38.0,79.0,0.481,11.0,30.0,0.367,19.0,27.0,0.704,...,100.0,40.1,206.0,111.0,DAL,102,0,2021,2020-12-23,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,240.0,50.0,92.0,0.543,14.0,36.0,0.389,19.0,25.0,0.760,...,100.0,32.9,185.0,133.0,WAS,130,1,2021,2020-12-31,True
130,240.0,42.0,87.0,0.483,16.0,35.0,0.457,19.0,24.0,0.792,...,50.0,46.6,187.0,128.0,CLE,99,0,2021,2020-12-31,False
131,240.0,37.0,82.0,0.451,12.0,23.0,0.522,13.0,24.0,0.542,...,40.0,38.7,300.0,111.0,IND,119,1,2021,2020-12-31,True
132,240.0,33.0,95.0,0.347,7.0,28.0,0.250,19.0,21.0,0.905,...,50.0,28.8,150.0,98.0,PHI,116,0,2021,2020-12-31,True
133,240.0,35.0,84.0,0.417,12.0,34.0,0.353,13.0,19.0,0.684,...,23.0,34.3,182.0,110.0,PHO,106,0,2021,2020-12-31,True

In [147]:
# target indicates if the team lost their next game

def add_target(team):
    team ["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

In [148]:
df[df["team"] == "BOS"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
16,240.0,48.0,101.0,0.475,18.0,40.0,0.450,8.0,11.0,0.727,...,42.3,187.0,130.0,MIL,121,0,2021,2020-12-23,True,True
32,240.0,37.0,98.0,0.378,8.0,27.0,0.296,13.0,19.0,0.684,...,37.1,300.0,112.0,BRK,123,0,2021,2020-12-25,True,False
58,240.0,40.0,79.0,0.506,9.0,23.0,0.391,18.0,24.0,0.750,...,30.9,144.0,112.0,IND,108,1,2021,2020-12-27,False,True
103,240.0,40.0,80.0,0.500,9.0,22.0,0.409,27.0,37.0,0.730,...,27.7,170.0,126.0,IND,111,1,2021,2020-12-29,True,True
119,240.0,49.0,91.0,0.538,16.0,39.0,0.410,12.0,14.0,0.857,...,30.1,163.0,127.0,MEM,107,0,2021,2020-12-30,True,NaN

In [149]:
df["target"][pd.isnull(df["target"])]

93     NaN
96     NaN
104    NaN
105    NaN
108    NaN
109    NaN
110    NaN
111    NaN
112    NaN
113    NaN
114    NaN
115    NaN
116    NaN
117    NaN
118    NaN
119    NaN
120    NaN
121    NaN
122    NaN
123    NaN
124    NaN
125    NaN
126    NaN
127    NaN
128    NaN
129    NaN
130    NaN
131    NaN
132    NaN
133    NaN
Name: target, dtype: object

In [150]:
def true_false_conversion(x):
    if x == True:
        return 1
    elif x == False:
        return 0
    else:
        return 2
df["target"] = df["target"].apply(true_false_conversion)

In [155]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,True,1
1,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,False,0
2,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True,1
3,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False,1
4,240.0,38.0,79.0,0.481,11.0,30.0,0.367,19.0,27.0,0.704,...,40.1,206.0,111.0,DAL,102,0,2021,2020-12-23,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,240.0,50.0,92.0,0.543,14.0,36.0,0.389,19.0,25.0,0.760,...,32.9,185.0,133.0,WAS,130,1,2021,2020-12-31,True,2
130,240.0,42.0,87.0,0.483,16.0,35.0,0.457,19.0,24.0,0.792,...,46.6,187.0,128.0,CLE,99,0,2021,2020-12-31,False,2
131,240.0,37.0,82.0,0.451,12.0,23.0,0.522,13.0,24.0,0.542,...,38.7,300.0,111.0,IND,119,1,2021,2020-12-31,True,2
132,240.0,33.0,95.0,0.347,7.0,28.0,0.250,19.0,21.0,0.905,...,28.8,150.0,98.0,PHI,116,0,2021,2020-12-31,True,2
133,240.0,35.0,84.0,0.417,12.0,34.0,0.353,13.0,19.0,0.684,...,34.3,182.0,110.0,PHO,106,0,2021,2020-12-31,True,2

In [156]:
df["won"].value_counts()

False    68
True     66
Name: won, dtype: int64

In [157]:
df["target"].value_counts()

0    53
1    51
2    30
Name: target, dtype: int64

In [159]:
# Check how many columns have null values
nulls = pd.isnull(df)

In [162]:
nulls = nulls.sum()

In [164]:
nulls[nulls > 0]

+/-             134
mp_max          134
mp_max.1        134
+/-_opp         134
mp_max_opp      134
mp_max_opp.1    134
dtype: int64

In [ ]:
# Delete previous cell columns